### ISSUE TITLE
add youtube link to site

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/mossleyheritage#6]
## Acceptance criteria

- [x] I can see the sentance “Visit our Youtube channel to enjoy audio and video stories along all five trails” in keep up to date box
- [x] I can see a link button to [youtube channel](https://youtube.com/@MossleyHeritageProject) with text below description sentence in AC1
- [x] The button reads "visit our YouTube channel"
- [x] styles match the existing facebook related content
- [x] the above features on the trails page, home page and contact page

## questions?

- there is a 'keep up to date' box on every page, why are these changes only requested on some page?

## notes

![image](https://github.com/geeksforsocialchange/mossleyheritage/assets/6824891/a4f568fe-e76b-4141-852d-1f5585e2d29e)

**Comment by ivan-kocienski-gfsc** [comment]
verified

## Home

![youtube-link-1-home](https://github.com/geeksforsocialchange/mossleyheritage/assets/109223824/95b16c49-a0d4-4def-8f33-688417a6da3b)

## Trails

![youtube-link-2-trails](https://github.com/geeksforsocialchange/mossleyheritage/assets/109223824/957cd95c-03d5-4485-b497-7bd6c4b9d735)

## History

![youtube-link-3-history](https://github.com/geeksforsocialchange/mossleyheritage/assets/109223824/72a5719d-de47-4eae-babb-65348a2d71cf)

## Visit

![youtube-link-4-visit](https://github.com/geeksforsocialchange/mossleyheritage/assets/109223824/153045ea-f149-4719-ab11-6798e74ab05c)

## Contact

![youtube-link-5-contact](https://github.com/geeksforsocialchange/mossleyheritage/assets/109223824/117c26fb-cbea-4130-9f37-d335a5e795d9)
