### ISSUE TITLE
date correction

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/mossleyheritage#7]
## Acceptance criteria

- [ ] change date to `1998`  in our history -> 1989 -> "Longlands Mill was purchased by Emmaus Mossley."

## Notes

![image](https://github.com/geeksforsocialchange/mossleyheritage/assets/6824891/fdc27755-69fe-4440-98e8-aea212d8f79e)

**Comment by ivan-kocienski-gfsc** [comment]
Verification

![Screenshot_2023-07-26_10-28-45](https://github.com/geeksforsocialchange/mossleyheritage/assets/109223824/bf6b5a63-ff38-4ae3-92ae-bbd0f7385393)
